### ISSUE TITLE
The Game process took too long to launch

### ISSUE THREAD

**Issue by JazRav** [jayclassless/SteamBattleNetLauncher#3]
Every time I launch anything with this, it does this

**Comment by hExPY** [comment]
Guess we have the same problem. #4 

Gonna close my issue.

**Comment by hExPY** [comment]
@DrBrobot you can use https://github.com/dafzor/bnetlauncher which works fine for me :-)

**Comment by jayclassless** [comment]
Should be fixed in the newest version.

Sorry for the delay.
